db:
  image: percona:5.6
  volumes:
  - ./data:/var/lib/mysql
  environment:
  - MYSQL_DATABASE=magento2
  - MYSQL_ROOT_PASSWORD=secret
  ports:
  - 3306:3306
php:
  image: lazyguru/mage2php
  volumes:
  - ./magento:/var/www/html
  links:
  - db
nginx:
  image: lazyguru/mage2nginx
  volumes:
  - ./magento:/var/www/html
  links:
  - php
varnish:
  image: lazyguru/mage2varnish
  ports:
  - 8080:80
  links:
  - nginx
